name: Build and deploy JAR

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: docker-deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK@17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build project with Maven
        run: mvn package --file pom.xml -DskipTests

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: spring-weather-prediction
          path: |
            target/*.jar

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: pvkr/spring-weather-prediction:latest


